"""Tree-sitter symbol index: definitions + call references, cached in SQLite.

This is the flagship real-time-discipline module: tree-sitter parsing and
SQLite writes are CPU-bound, so *all* of it runs inside asyncio.to_thread().
If cold-indexing a huge repo is ever too slow, the M5+ optimization is to swap
the to_thread call for a ProcessPoolExecutor — the async interface stays put.

Which languages are understood is a table, not a literal: see languages.py.
M14 added typescript, tsx, javascript, and go alongside python, and the file
walk takes its extension set from that table — a grammar added without also
touching the walk indexes nothing at all, silently.
"""

from __future__ import annotations

import asyncio
import os
import sqlite3
import threading
import time
from pathlib import Path

from tree_sitter import Parser, QueryCursor

from pyrrhon.core.tools.base import Tool
from pyrrhon.core.tools.languages import (
    CompiledLanguage,
    LanguageSpec,
    compiled,
    spec_for_extension,
)
from pyrrhon.core.tools.repo import SKIP_DIRS

_SCHEMA = """
CREATE TABLE IF NOT EXISTS files (path TEXT PRIMARY KEY, mtime REAL, lang TEXT);
CREATE TABLE IF NOT EXISTS symbols (name TEXT, kind TEXT, file TEXT, line INTEGER, lang TEXT);
CREATE TABLE IF NOT EXISTS refs (name TEXT, file TEXT, line INTEGER);
CREATE TABLE IF NOT EXISTS imports (file TEXT, module TEXT);
CREATE INDEX IF NOT EXISTS idx_symbols_name ON symbols (name);
CREATE INDEX IF NOT EXISTS idx_refs_name ON refs (name);
CREATE INDEX IF NOT EXISTS idx_imports_module ON imports (module);
CREATE INDEX IF NOT EXISTS idx_imports_file ON imports (file);
"""

# Bumped whenever the shape above changes. 1 was the implicit M4-M13 schema
# (no `lang` column); 2 added it.
_SCHEMA_VERSION = 2


def _ensure_schema(conn: sqlite3.Connection) -> None:
    """Create or REBUILD the cache when its shape changed.

    CREATE TABLE IF NOT EXISTS will not add a column to a table that already
    exists, so without this an M13 cache.db keeps the old shape and every
    query naming `lang` fails. The cache is a derived artifact — every row can
    be regenerated by reparsing — so a version bump drops and rebuilds rather
    than migrating. That is cheaper to write, impossible to get subtly wrong,
    and costs one cold index on the first run after an upgrade.
    """
    version = conn.execute("PRAGMA user_version").fetchone()[0]
    if version != _SCHEMA_VERSION:
        for table in ("files", "symbols", "refs", "imports"):
            conn.execute(f"DROP TABLE IF EXISTS {table}")
        conn.executescript(_SCHEMA)
        conn.execute(f"PRAGMA user_version = {_SCHEMA_VERSION}")
        conn.commit()
    else:
        conn.executescript(_SCHEMA)


def _module_name(rel: str) -> str:
    parts = list(Path(rel).with_suffix("").parts)
    if parts and parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def _node_text(node) -> str:
    """A capture's source text. tree-sitter types `.text` as bytes | None —
    None only for a node built without its source buffer, which cannot happen
    for captures off a freshly parsed tree, so an empty string is the safe
    degradation rather than an AttributeError mid-index."""
    return (node.text or b"").decode("utf-8")


def _package_of(rel: str) -> str:
    parts = list(Path(rel).with_suffix("").parts)
    if parts:
        parts.pop()  # __init__ or the module file — either way, drop it
    return ".".join(parts)


# Within one model turn the index tools (repo_map, find_symbol,
# list_dependencies) fire back-to-back, and each ensure_fresh() re-walks the
# whole tree stat'ing every .py file. Collapsing calls inside this window into
# one walk is the biggest per-turn latency lever on large repos; a couple of
# seconds of staleness is invisible in a voice conversation (turns are slower).
# Raised from 2.0s in M10. A read-only agent rarely races its own repo, and
# the mtime check makes the walk cheap only in the sense that it avoids
# re-parsing — the tree walk itself still stats every source file, which is
# the cost on a large repo. Capped at 10s rather than something larger on
# purpose: the grounding gate verifies that a cited line is IN RANGE, not that
# it is the RIGHT line, so a stale index can produce a right-file/stale-line
# citation that the gate happily passes. Ten seconds bounds that window to
# roughly one conversational turn.
INDEX_FRESH_TTL_SEC = 10.0


class SymbolIndex:
    """Lazy per-repo symbol index. __init__ does no I/O — first use builds it."""

    def __init__(self, root: Path):
        self.root = root.resolve()
        self.db_path = self.root / ".pyrrhon" / "cache.db"
        self._lock = asyncio.Lock()  # serializes concurrent ensure_fresh calls
        self._last_fresh_at: float | None = None  # monotonic; None = never walked
        self._db: sqlite3.Connection | None = None
        # Every DB touch runs in a to_thread worker; serialize the one shared
        # connection across those threads with a plain Lock.
        self._db_lock = threading.Lock()
        # Bumped whenever a file is reparsed or forgotten. Derived views keyed
        # on it (currently the repo map) stay valid until the index actually
        # changes, rather than being rebuilt on a timer.
        self._generation = 0
        self._repo_map_cache: tuple[int, int, str] | None = None

    async def ensure_fresh(self, force: bool = False) -> None:
        async with self._lock:
            now = time.monotonic()
            if (
                not force
                and self._last_fresh_at is not None
                and now - self._last_fresh_at < INDEX_FRESH_TTL_SEC
            ):
                return  # walked moments ago (same turn) — skip the re-scan
            await asyncio.to_thread(self._sync_ensure_fresh)
            self._last_fresh_at = time.monotonic()

    async def find_symbol(self, name: str) -> list[tuple[str, int, str]]:
        return await asyncio.to_thread(self._sync_find_symbol, name)

    async def find_references(self, name: str) -> list[tuple[str, int]]:
        return await asyncio.to_thread(self._sync_find_references, name)

    async def list_imports(self, rel_file: str) -> list[str]:
        return await asyncio.to_thread(self._sync_list_imports, rel_file)

    async def find_importers(self, rel_file: str) -> list[str]:
        return await asyncio.to_thread(self._sync_find_importers, rel_file)

    async def build_repo_map(self, max_chars: int = 6000) -> str:
        return await asyncio.to_thread(self._sync_build_repo_map, max_chars)

    async def languages(self) -> dict[str, int]:
        """Indexed file count per language, busiest first."""
        return await asyncio.to_thread(self._sync_languages)

    # -- everything below runs in a worker thread ---------------------------

    def _db_conn(self) -> sqlite3.Connection:
        """The one persistent connection, shared across to_thread workers and
        serialized by _db_lock. Opened lazily; the schema runs once. Replaces the
        old connect()+executescript() that ran on every single query."""
        if self._db is None:
            self.db_path.parent.mkdir(exist_ok=True)
            # check_same_thread=False: to_thread runs us on pool threads. Safe
            # because every use below is wrapped in `with self._db_lock`.
            self._db = sqlite3.connect(self.db_path, check_same_thread=False)
            _ensure_schema(self._db)
        return self._db

    def _iter_files_with_mtime(self):
        """Yield (path, mtime, spec) for every indexable file, pruning SKIP_DIRS.

        The extension set comes from the language table, not a literal: M10's
        postscript recorded that a hardcoded '.py' here means a newly added
        grammar never sees a file, which is a silent failure rather than an
        error.

        Uses os.scandir so each mtime comes from the DirEntry stat cached by
        the single directory read, not a fresh per-file Path.stat() syscall.
        On Windows that is ~160x faster — per-file stat syscalls dominate the
        walk — with identical freshness: every file is still stat'd each call.
        """
        stack = [str(self.root)]
        while stack:
            try:
                scan = os.scandir(stack.pop())
            except OSError:
                continue  # unreadable dir: skip, don't abort the whole index
            with scan:
                for entry in scan:
                    if entry.is_dir(follow_symlinks=False):
                        if entry.name not in SKIP_DIRS:
                            stack.append(entry.path)
                        continue
                    spec = spec_for_extension(os.path.splitext(entry.name)[1])
                    if spec is not None and entry.is_file(follow_symlinks=False):
                        yield Path(entry.path), entry.stat().st_mtime, spec

    def _sync_ensure_fresh(self) -> None:
        with self._db_lock:
            conn = self._db_conn()
            known: dict[str, float] = dict(
                conn.execute("SELECT path, mtime FROM files")
            )
            # Per-CALL construction, one parser per language: Parser objects are
            # not thread-safe and this runs in a to_thread worker, so a cache on
            # self would be shared across workers. Built via py-tree-sitter
            # (bytes API); the pack's get_parser returns a rust-native parser
            # with a different (str-based) interface.
            parsers: dict[str, Parser] = {}
            seen: set[str] = set()
            for path, mtime, spec in self._iter_files_with_mtime():
                rel = path.relative_to(self.root).as_posix()
                seen.add(rel)
                if known.get(rel) == mtime:
                    continue  # unchanged — the whole point of the mtime column
                unit = compiled(spec)  # grammar loaded on first file of its kind
                parser = parsers.get(spec.name)
                if parser is None:
                    parser = parsers[spec.name] = Parser(unit.language)
                self._reparse(conn, parser, unit, spec, path, rel, mtime)
                self._generation += 1
            for rel in set(known) - seen:  # files deleted since last index
                self._forget(conn, rel)
                self._generation += 1
            conn.commit()

    def _reparse(
        self,
        conn: sqlite3.Connection,
        parser,
        unit: CompiledLanguage,
        spec: LanguageSpec,
        path: Path,
        rel: str,
        mtime: float,
    ) -> None:
        tree = parser.parse(path.read_bytes())
        conn.execute("DELETE FROM symbols WHERE file = ?", (rel,))
        conn.execute("DELETE FROM refs WHERE file = ?", (rel,))
        conn.execute("DELETE FROM imports WHERE file = ?", (rel,))
        symbols = [
            (_node_text(node), capture_name.removeprefix("def."), rel,
             node.start_point.row + 1, spec.name)
            for capture_name, nodes in QueryCursor(unit.defs).captures(tree.root_node).items()
            for node in nodes
        ]
        if symbols:  # one executemany beats N executes on a cold build
            conn.executemany(
                "INSERT INTO symbols (name, kind, file, line, lang) VALUES (?, ?, ?, ?, ?)",
                symbols,
            )
        refs = [
            (_node_text(node), rel, node.start_point.row + 1)
            for nodes in QueryCursor(unit.refs).captures(tree.root_node).values()
            for node in nodes
        ]
        if refs:
            conn.executemany("INSERT INTO refs (name, file, line) VALUES (?, ?, ?)", refs)
        package = _package_of(rel)
        imports = [
            (rel, module)
            for nodes in QueryCursor(unit.imports).captures(tree.root_node).values()
            for node in nodes
            for module in spec.parse_imports(_node_text(node), package)
        ]
        if imports:
            conn.executemany("INSERT INTO imports (file, module) VALUES (?, ?)", imports)
        conn.execute(
            "INSERT OR REPLACE INTO files (path, mtime, lang) VALUES (?, ?, ?)",
            (rel, mtime, spec.name),
        )

    def _forget(self, conn: sqlite3.Connection, rel: str) -> None:
        conn.execute("DELETE FROM symbols WHERE file = ?", (rel,))
        conn.execute("DELETE FROM refs WHERE file = ?", (rel,))
        conn.execute("DELETE FROM imports WHERE file = ?", (rel,))
        conn.execute("DELETE FROM files WHERE path = ?", (rel,))

    def _sync_find_symbol(self, name: str) -> list[tuple[str, int, str]]:
        with self._db_lock:
            rows = self._db_conn().execute(
                "SELECT file, line, kind FROM symbols WHERE name = ? ORDER BY file, line",
                (name,),
            ).fetchall()
        return [(file, line, kind) for file, line, kind in rows]

    def _sync_find_references(self, name: str) -> list[tuple[str, int]]:
        with self._db_lock:
            rows = self._db_conn().execute(
                "SELECT file, line FROM refs WHERE name = ? ORDER BY file, line",
                (name,),
            ).fetchall()
        return [(file, line) for file, line in rows]

    def _sync_list_imports(self, rel_file: str) -> list[str]:
        with self._db_lock:
            rows = self._db_conn().execute(
                "SELECT DISTINCT module FROM imports WHERE file = ? ORDER BY module",
                (rel_file,),
            ).fetchall()
        return [module for (module,) in rows]

    def _sync_languages(self) -> dict[str, int]:
        with self._db_lock:
            rows = self._db_conn().execute(
                "SELECT lang, COUNT(*) FROM files GROUP BY lang ORDER BY COUNT(*) DESC"
            ).fetchall()
        return {lang: count for lang, count in rows if lang}

    def _sync_find_importers(self, rel_file: str) -> list[str]:
        module = _module_name(rel_file)
        with self._db_lock:
            rows = self._db_conn().execute(
                "SELECT DISTINCT file FROM imports WHERE module = ? "
                "AND file != ? ORDER BY file",
                (module, rel_file),
            ).fetchall()
        return [file for (file,) in rows]

    def _sync_build_repo_map(self, max_chars: int) -> str:
        """Aider-style repo map: files ordered by how much the rest of the
        repo references their symbols; top symbols listed per file. Pure
        counting over the refs table — no graph traversal, so import cycles
        cannot recurse.

        Memoised on the index generation. The query runs a correlated
        subquery per symbol row and then rebuilds the whole string, and
        nothing about the result can change while the index does not — so a
        repeat call within a turn, or across turns with no edits, is free.
        """
        cached = self._repo_map_cache
        if cached is not None and cached[0] == self._generation and cached[1] == max_chars:
            return cached[2]
        with self._db_lock:
            rows = self._db_conn().execute(
                """
                SELECT s.file, s.name, s.kind, s.line,
                       (SELECT COUNT(*) FROM refs r
                         WHERE r.name = s.name AND r.file != s.file) AS uses
                FROM symbols s
                ORDER BY s.file, uses DESC, s.line
                """
            ).fetchall()
        by_file: dict[str, list[tuple[str, str, int, int]]] = {}
        for file, name, kind, line, uses in rows:
            by_file.setdefault(file, []).append((name, kind, line, uses))
        ranked = sorted(
            by_file.items(),
            key=lambda item: sum(u for *_ignored, u in item[1]),
            reverse=True,
        )
        lines: list[str] = []
        used = 0
        for file, symbols in ranked:
            block = [f"{file}:"]
            for name, kind, line, uses in symbols[:8]:
                suffix = f" ({uses} refs)" if uses else ""
                block.append(f"  {kind} {name}:{line}{suffix}")
            chunk = "\n".join(block)
            if used + len(chunk) + 1 > max_chars:
                lines.append("…[truncated — ask about specific files]")
                break
            lines.append(chunk)
            used += len(chunk) + 1
        rendered = "\n".join(lines) or "No symbols indexed yet."
        self._repo_map_cache = (self._generation, max_chars, rendered)
        return rendered


class FindSymbolTool(Tool):
    name = "find_symbol"
    description = (
        "Find where a function or class is defined. Returns 'path:line: kind name' "
        "for each definition — cite these locations."
    )
    parameters = {
        "type": "object",
        "properties": {
            "name": {"type": "string", "description": "Exact symbol name, e.g. 'greet'"},
        },
        "required": ["name"],
    }

    def __init__(self, index: SymbolIndex):
        self.index = index

    async def run(self, name: str) -> str:
        await self.index.ensure_fresh()
        rows = await self.index.find_symbol(name)
        if not rows:
            return "No matches."
        return "\n".join(f"{file}:{line}: {kind} {name}" for file, line, kind in rows)


class FindReferencesTool(Tool):
    name = "find_references"
    description = (
        "Find call sites of a function or method by name. Returns 'path:line' per "
        "reference — answers 'what calls this?' / 'what breaks if I change this?'."
    )
    parameters = {
        "type": "object",
        "properties": {
            "name": {"type": "string", "description": "Exact symbol name, e.g. 'greet'"},
        },
        "required": ["name"],
    }

    def __init__(self, index: SymbolIndex):
        self.index = index

    async def run(self, name: str) -> str:
        await self.index.ensure_fresh()
        rows = await self.index.find_references(name)
        if not rows:
            return "No matches."
        return "\n".join(f"{file}:{line}" for file, line in rows)


class DependenciesTool(Tool):
    name = "list_dependencies"
    description = (
        "Show a Python file's import edges both ways: modules it imports, and "
        "repo files that import it. Answers 'what depends on this?' / "
        "'what does this rely on?' before you trace call sites."
    )
    parameters = {
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "Repo-relative .py path"},
        },
        "required": ["path"],
    }

    def __init__(self, index: SymbolIndex):
        self.index = index

    async def run(self, path: str) -> str:
        await self.index.ensure_fresh()
        imports = await self.index.list_imports(path)
        importers = await self.index.find_importers(path)
        if not imports and not importers:
            return f"No import edges recorded for {path} (is it a Python file in the repo?)."
        lines = ["imports:"]
        lines += [f"  {m}" for m in imports] or ["  (none)"]
        lines.append("imported by:")
        lines += [f"  {f}" for f in importers] or ["  (none)"]
        return "\n".join(lines)


class RepoMapTool(Tool):
    name = "repo_map"
    description = (
        "Ranked overview of the whole repo: the most-referenced classes and "
        "functions per file, hottest files first. Call this FIRST on a "
        "codebase you haven't explored — it tells you where to look."
    )
    parameters = {"type": "object", "properties": {}}

    def __init__(self, index: SymbolIndex):
        self.index = index

    async def run(self) -> str:
        await self.index.ensure_fresh()
        return await self.index.build_repo_map()
